# Generated by Django 3.0.4 on 2020-03-08 18:23

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Regex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern', models.TextField(verbose_name='Your pattern')),
                ('text', models.TextField(help_text='Test text', verbose_name='Your text')),
                ('match_type', models.CharField(choices=[('match', 'match'), ('findall', 'findall'), ('search', 'search')], default='match', max_length=7)),
                ('flags', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('re.I', 'ignorecase'), ('re.M', 'rmultiline'), ('re.S', 'dotall'), ('re.U', 'uunicode'), ('re.L', 'locale'), ('re.X', 'verbose')], default=False, max_length=29)),
            ],
        ),
    ]
